"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import warnings
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Suppress ChromaDB telemetry warnings
os.environ['ANONYMIZED_TELEMETRY'] = 'False'

# Suppress harmless deprecation warnings from third-party libraries
try:
    from cryptography.utils import CryptographyDeprecationWarning
    warnings.filterwarnings(
        'ignore',
        category=CryptographyDeprecationWarning,
        module='pypdf._crypt_providers._cryptography'
    )
    warnings.filterwarnings(
        'ignore',
        message='.*ARC4 has been moved.*',
        category=CryptographyDeprecationWarning
    )
except ImportError:
    # Fallback if CryptographyDeprecationWarning is not available
    warnings.filterwarnings(
        'ignore',
        message='.*ARC4 has been moved.*'
    )

# Suppress ChromaDB/PostHog telemetry warnings
warnings.filterwarnings(
    'ignore',
    message=r'.*Failed to send telemetry.*',
    category=UserWarning
)
warnings.filterwarnings(
    'ignore',
    message=r'.*capture\(\) takes.*',
    category=UserWarning
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-%@u+*@!blua1@_yn3v+$!fdgc@^=z3b-s(6^5#f#*xo8!jl#so')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'authentication',
    'documents',
    'leads',
    'campaigns',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Use bcrypt as primary password hasher
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.BCryptPasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# JWT Configuration
JWT_SECRET_KEY = os.getenv('JWT_SECRET_KEY', 'jwt-secret-key-change-in-production')
JWT_ALGORITHM = os.getenv('JWT_ALGORITHM', 'HS256')
JWT_ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv('JWT_ACCESS_TOKEN_EXPIRE_MINUTES', '30'))

# Email Configuration (for password reset)
# SSL Configuration for email (fixes certificate verification issues on macOS)
# Set EMAIL_SSL_DISABLE_VERIFY=True in .env to disable SSL verification (development only)
EMAIL_SSL_DISABLE_VERIFY = os.getenv('EMAIL_SSL_DISABLE_VERIFY', 'False').strip().lower() == 'true'

# Set EMAIL_BACKEND in .env to send real emails:
#   - 'services.custom_email_backend.CustomSMTPEmailBackend' (recommended - handles SSL issues)
#   - 'django.core.mail.backends.smtp.EmailBackend' (standard SMTP)
# Default is console backend (emails printed to terminal)
email_backend_env = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend').strip()
# If using SMTP and SSL verification is disabled, use custom backend
if 'smtp' in email_backend_env.lower() and EMAIL_SSL_DISABLE_VERIFY:
    EMAIL_BACKEND = 'services.custom_email_backend.CustomSMTPEmailBackend'
else:
    EMAIL_BACKEND = email_backend_env

EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')

# Test Email Configuration (for testing/demo - all emails will be sent here)
TEST_EMAIL = os.getenv('TEST_EMAIL', 'nayabiftikhar6633@gmail.com')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'nayabiftikhar6633@gmail.com')

# Sales Team Email (for notifications when leads reach goal outcomes)
SALES_TEAM_EMAIL = os.getenv('SALES_TEAM_EMAIL', DEFAULT_FROM_EMAIL)

# IMAP Configuration (for capturing email replies)
IMAP_HOST = os.getenv('IMAP_HOST', 'imap.gmail.com')
IMAP_PORT = int(os.getenv('IMAP_PORT', '993'))
IMAP_USE_SSL = os.getenv('IMAP_USE_SSL', 'True') == 'True'
IMAP_USER = os.getenv('IMAP_USER', '')
IMAP_PASSWORD = os.getenv('IMAP_PASSWORD', '')
IMAP_MAILBOX = os.getenv('IMAP_MAILBOX', 'INBOX')

# Static files
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Login redirect
LOGIN_URL = '/auth/login/'
LOGIN_REDIRECT_URL = '/'

# ChromaDB Configuration
CHROMA_PERSIST_DIRECTORY = BASE_DIR / 'data' / 'chromadb'
CHROMA_COLLECTION_BROCHURES = 'brochures'

# Embeddings Configuration
EMBEDDING_MODEL = os.getenv('EMBEDDING_MODEL', 'all-MiniLM-L6-v2')

# Ensure data directories exist
os.makedirs(BASE_DIR / 'data' / 'chromadb', exist_ok=True)
os.makedirs(BASE_DIR / 'data' / 'brochures', exist_ok=True)
os.makedirs(BASE_DIR / 'media', exist_ok=True)
