# Generated by Django 5.2.8 on 2025-11-10 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignlead',
            name='personalized_message',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('customer', 'Customer'), ('agent', 'Agent')], max_length=20)),
                ('message', models.TextField()),
                ('agent_tool_used', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='campaigns.campaignlead')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
