# Generated by Django 5.2.8 on 2025-11-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaignlead_personalized_message_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignlead',
            name='email_message_id',
            field=models.CharField(blank=True, help_text='Email Message-ID header for tracking replies', max_length=500),
        ),
        migrations.AddField(
            model_name='conversation',
            name='email_in_reply_to',
            field=models.CharField(blank=True, help_text='Email In-Reply-To header for threading', max_length=500),
        ),
        migrations.AddField(
            model_name='conversation',
            name='email_message_id',
            field=models.CharField(blank=True, help_text='Email Message-ID header', max_length=500),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['email_message_id'], name='campaigns_c_email_m_feeb82_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['email_in_reply_to'], name='campaigns_c_email_i_31d2b3_idx'),
        ),
    ]
