# Generated by Django 5.2.8 on 2025-11-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaignlead_email_message_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='auto_reply_processed',
            field=models.BooleanField(default=False, help_text='Whether automated reply has been processed'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='sales_team_notified',
            field=models.BooleanField(default=False, help_text='Whether sales team was notified for this conversation'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['auto_reply_processed', 'sender'], name='campaigns_c_auto_re_7032f8_idx'),
        ),
    ]
